# _config.yml
title: My Blog
description: 个人技术博客
author: Your Name
url: "https://username.github.io"
baseurl: ""

# 主题设置
theme: minima

# 博客设置
permalink: /:year/:month/:day/:title/
paginate: 10
paginate_path: "/page:num/"

# Markdown设置
markdown: kramdown
highlighter: rouge

# 社交链接
github_username: username
twitter_username: username
email: your-email@example.com

# 导航菜单
nav_pages:
  - name: 首页
    url: /
  - name: 文章
    url: /posts
  - name: 分类
    url: /categories
  - name: 关于
    url: /about

# 评论系统 (使用Gitalk)
gitalk:
  enable: true
  clientID: your-client-id
  clientSecret: your-client-secret
  repo: username.github.io
  owner: username
  admin: [username]